config/routes.rb
Rails.application.routes.draw do
  root to: 'spaces#index'
  devise_for :users

  get 'spaces/search', to: 'spaces#search'
  resources :spaces do
    resources :bookings, only:[:new, :create, :destroy, :show]
  end

  resources :bookings, only: [:index]
  # uncomment this on master:
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :space
  belongs_to :user

  validates :start_time, presence: true
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :bookings, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { in: 3..30, wrong_length: "Please choose a name with characters count between 3 and 30." }
  validates :address, presence: true
  validates :description, length: { maximum: 200, too_long: "%{count} characters is the maximum allowed." }
  validates :price_per_hour, presence: true, numericality: {  greater_than_or_equal_to: 0 } # ERROR HERE
  geocoded_by :address #we have to change this to the interpolation mode {address} {city} {country}
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         #test comment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!, :store_location
      # before_action :store_location


  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def store_location
      # store last url as long as it isn't a /users path
    session[:previous_url] = request.fullpath unless request.fullpath =~ /\/users/
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]
  before_action :set_space, only: [ :new, :create ]

  def index
    @bookings = policy_scope(Booking.where(user: current_user))
  end

  def show
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.space = @space
    @booking.user = current_user
    authorize @booking
    @price_hour = @space.price_per_hour
    @total_price = @price_hour * @booking.duration
    @booking.total_price = @total_price.to_i

    if @booking.save
      redirect_to bookings_path(@space, @booking)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking.delete
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit( :start_time, :duration)
  end

  def set_space
    @space = Space.find(params[:space_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only: [:show, :edit, :update, :delete]
  skip_after_action :verify_authorized, only: :search
  skip_before_action :authenticate_user!, only: [ :index, :search, :show ]
  layout 'no_footer', only: [:index, :search]


  def index
    @spaces = policy_scope(Space.where.not(latitude: nil, longitude: nil))

    #### CODE FOR GEOCODING


    ##### END OF CODE FOR GEOCODING
  end

  def show
    @booking = Booking.new
    @spaces = policy_scope(Space.where(latitude: @space.latitude, longitude: @space.longitude))
    @markers = @spaces.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude#,
        # infoWindow: { content: render_to_string(partial: "/spaces/map_box", locals: { flat: flat }) }
      }
    end
  end

  def create
    @space = Space.new(space_params)
    @space.image_url = (1..23).to_a.sample.to_s
    if @space.save
      redirect_to spaces_path
    else
      render :new
    end
    authorize @space
  end

  def new
    @space = Space.new
    authorize @space
  end

  def edit
  end

  def update
    @space.update(space_params)
    redirect_to spaces_path
  end

  def destroy
    @space.destroy
    redirect_to spaces_path
  end

  def search
    @spaces = policy_scope(Space.where.not(latitude: nil, longitude: nil))
    if params[:query].present?
        @spaces = Space.near(params[:query], 30)
    end

    @markers = @spaces.map do |space|
      {
        lat: space.latitude,
        lng: space.longitude#,
        # infoWindow: { content: render_to_string(partial: "/spaces/map_box", locals: { flat: flat }) }
      }
    end
  end


  private

  def set_space
    @space = Space.find(params[:id])
    authorize @space
  end

  def space_params
    params.require(:space).permit(:name, :address, :description, :price_per_hour )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h1>Bookings#edit</h1>
<p>Find me in app/views/bookings/edit.html.erb</p>

app/views/bookings/index.html.erb
<div class="container show-container">
  <h1><strong>Hello!</strong></h1>
  <h3>Check out your bookings:</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Space name</th>
        <th>Date</th>
        <th>Start time</th>
        <th>Duration</th>
        <th>Price</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.space.name %></td>
        <td><%= booking.start_time.strftime('%D') %></td>
        <td><%= booking.start_time.strftime('%H') %></td>
        <td><%= booking.duration %></td>
        <td><%= booking.total_price.to_i %>€</td>
        <td><%= link_to "Info", space_path(booking.space), class: "btn btn-info" %></td>
        <td><%= link_to "Delete", space_booking_path(booking.space, booking), method: :delete, class: "btn btn-info" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row show-container">
    <div class="text-center">
      <h2> <%= @space.name  %> </h2>
    </div>
      <%= simple_form_for [@space, @booking] do |f| %>
        <%= f.input :start_time, as: :datetime, discard_minute: true, order: [:month, :day] %>
        <%= f.input :duration, input_html: { value: '1', min: '1', max: '3', step: 'any' }, label: 'Hours to book' %>
        <h3> Price per hour: <%= @space.price_per_hour.to_i  %>$ </h3>
        <%= f.submit "Book the space", class: "btn btn-danger" %>
      <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container show-container">
  <h1>YOU BOOKED THIS PLACE</h1>
  <h1> Total Price:   <%= @booking.total_price  %> $ </h1>
</div>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>JammBoxxSpace</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="page">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes'  %>
      <%= render 'shared/searchbar'  %>
      <%= yield %>
        <!--Le Wagonn templates for flash alerts -->
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    </div>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
    <%= yield :after_js %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>JammBoxxSpace</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="page">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes'  %>
      <%= render 'shared/searchbar'  %>
      <%= yield %>
        <!--Le Wagonn templates for flash alerts -->
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
    <%= yield :after_js %>
  </body>
</html>

app/views/layouts/no_footer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>JammBoxxSpace</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <div class="page">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes'  %>
      <%= render 'shared/searchbar'  %>
      <%= yield %>
        <!--Le Wagonn templates for flash alerts -->
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
    <%= javascript_pack_tag "map" %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>navbar</h1>

app/views/shared/_banner.html.erb
<div class="banner" style="align-items: center; background-image: linear-gradient(to top, rgba(0, 0, 0, 0) 0, #000 200%),  url('<%= image_url("banner2.jpg") %>');">
  <div class="banner-content">
    <div class="lol">
      <h1><%= image_tag "jamspace.png", height: 150 %></h1>


    </div>
    <p>Rent unique places to play your next Jamm Sesh!</p>
<h2>
      <%= form_tag spaces_search_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "btn form-control",
          placeholder: "SEARCH A PLACE TO JAMM" %>
      <% end %>
</h2>
    </div>
</div>

app/views/shared/_cards.html.erb
<ul class="cards">
  <% @spaces.each do |space| %>
  <li class="cards__item">
    <div class="card">
      <div class="card__image"> <%= cl_image_tag(space.image_url,width: 400, height: 300, crop: :fill) %> </div>
      <div class="card__content">
        <div class="card__title"><%= space.name %></div>
        <p class="card__text"><%= space.description %> <br> <%= space.address %> $<%= space.price_per_hour.to_i %>/h</p>

        <%= link_to "more info", space_path(space), class: "btn btn--block card__btn" %>
      </div>
    </div>
  </li>
  <% end %>
</ul>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top <%=
(controller_name = "spaces" && action_name == "index") ? "" : "navbar-wagon-white" %> ">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "Grouplogo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Create a space", new_space_path , class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="notification">1</div>
        <div class="dropdown navbar-jammbox-avatar">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/geebabygee", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Bookings") %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar.html.erb
<!-- <div class="wrap">
   <div class="search">
      <button type="submit" class="search-box">
        <i class="fa fa-search"></i>
      <input type="text" class="search-term" placeholder="Try <<Lisbon>>">
     </button>
   </div>
</div> -->

<!--
<div class="wrap">
  <div class="search">
    <div class="row">
      <div class="col-sm-3">
        <div class="search-input-value">
          <div class="search-input-text">
            Choose your city
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="search-pink-rectangule">
          <div class="search-arrow">
            >
          </div>
        </div>
      </div>
      <div class="col-sm-3">
        <div class="search-pink-circle"></div>
      </div>
    </div>
 </div>
</div>
 -->

app/views/spaces/create.html.erb
<h1>Spaces#create</h1>
<p>Find me in app/views/spaces/create.html.erb</p>

app/views/spaces/edit.html.erb
<h1>Spaces#edit</h1>
<p>Find me in app/views/spaces/edit.html.erb</p>

app/views/spaces/index.html.erb
<%= render 'shared/banner' %>

<div class="huge-container">
  <div class="small-container">
    <div class="cards">
      <h3>Featured :</h3>

      <%= render 'shared/cards' %>
    </div>
      <% content_for :after_js do %>
        <%= javascript_pack_tag "home" %>
      <% end %>

  </div>
</div>
<!-- <%= render 'shared/footer' %> -->

app/views/spaces/new.html.erb
<div class="container form form-container">
  <h2>Creating a new space</h2>
  <div class="row">
      <%= simple_form_for @space do |f| %>
        <%= f.input :name, label: 'Name here please:' %>
        <%= f.input :address, label: 'Address here please:' %>
        <%= f.input :description, label: 'Description here please:' %>
        <%= f.input :price_per_hour, label: 'Price per hour', input_html: { min: '0', step: 'any' } %>
        <%= f.input :image_url, label: 'Image url here please:' %>
        <%= f.submit "Create", class: "btn btn-danger" %>
      <% end %>
  </div>
</div>

app/views/spaces/search.html.erb
<div class="search-box">
  <%= form_tag spaces_search_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a place to jamm" %>
  <% end %>
</div>


<div class="search-content" class="banner" style="align-items: center; background-image:  url('<%= image_url("banner_image.jpg") %>');">
  <div class="results">
    <div class="hidden-xs hidden-sm"
      id="map"
      data-markers="<%= @markers.to_json %>">

      </div>
      <div class="col-xs-12 col-sm-6 col-md-6" id="cardsinsearch">
      <%= render 'shared/cards' %>
    </div>
  </div>
</div>

app/views/spaces/show.html.erb
<div class="banner banner-show" style="background-image: url('<%= image_url("flat.jpg") %>');">
  <div class="banner-content">
    <h1><%=@space.name %></h1>
  </div>
</div>

<div class="grid">

  <div class="map"
      id="map" style="width: 99%;"
      data-markers="<%= @markers.to_json %>">
  </div>
  <div class="description">

    <p>
      <strong>Address:</strong>
      <br>
      <%= @space.address %>
    </p>
    <p>
      <strong>Description:</strong>
      <br>
      <%= @space.description %>
    </p>
  </div>
  <div class="booking-form">
      <%= simple_form_for [@space, @booking] do |f| %>
        <%= f.input :start_time, as: :datetime, discard_minute: true, order: [:month, :day] %>
        <%= f.input :duration, input_html: { value: '1', min: '1', max: '3', step: 'any', onChange: "calculatePrice()" }, label: 'Hours to book', id: "duration-input" %>
        <h4> Price per hour:
          <strong id= "price_per_hour"> <%= @space.price_per_hour.to_i  %></strong>
          €
        </h4>
        <%= f.submit "Book it", class: "btn btn-danger" %>
      <% end %>
  </div>
</div>

app/views/spaces/update.html.erb
<h1>Spaces#update</h1>
<p>Find me in app/views/spaces/update.html.erb</p>